const COMMANDS: &[&str] = &[
    "load_pet",
    "unload_pet",
    "trigger_event",
    "set_position",
    "register_sound",
    "register_sound_bytes",
    "set_tts",
    "say",
    "play_action",
    "show_bubble",
    "dismiss_bubble",
    "play_sequence",
    "stop_sequence",
    "set_behavior_config",
    "set_ambient_enabled",
    "get_stats",
    "set_stats",
    "save_state",
    "load_saved_state",
    "list_downloaded_pets",
    "get_state",
    "get_pet_meta",
    "get_actions",
    "get_position",
    "list_remote_pets",
    "search_remote_pets",
    "delete_saved_state",
    "clear_cache",
    "set_mood_config",
    "set_event_binding",
];

fn main() {
    tauri_plugin::Builder::new(COMMANDS).build();
}
